### ISSUE TITLE
Rethink display of achievements

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#116]
On the school homepage we're currently listing all achievements in the left hand nav bar.

I suggest that we keep only the most recently awarded achievement in the nav bar and then link through to the rest.

We might also want to update the "activities" cards at the top of the page to combine scoring and achievements. Perhaps the left card can be a summary of score and number of achievements.

**Comment by MattHelsby** [comment]
`badges_by_date(date: nil)` has an optional limit argument. 
We currently show the 6 most recent badges: [`@badges = @school.badges_by_date(limit: 6)`](https://github.com/BathHacked/energy-sparks/blob/65a44a02ff6ff4f5a0b0203c0e0c9ce077cd6a7f/app/controllers/schools_controller.rb#L19)
