### ISSUE TITLE
Display all possible achievements as well as those awarded.

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#117]
Schools should be able to see what achievements are possible and how to get them.

The achievements page should list those that they've been awarded and those that they have not yet achieved.

@MattHelsby easy to add?

**Comment by MattHelsby** [comment]
Yeah, `Merit::Badge.all` will give us a list of badges to subtract from. Although we currently use the same star image for all badges, so the page is going to look a bit star-heavy!
