### ISSUE TITLE
Merit causing server errors 

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#125]
I'm getting an intermittent error from the merit code. It manifests as an ActionController error:

```
undefined method `image' for #<Merit::Badge:0x007fd77af63d68>
```

Obviously it only occurs for schools that have an achievement. Restarting the server fixes the error and the page displays.

From in-browser error console:

```
>>  @school
=> #<School id: 69, name: "Twerton Infant School", school_type: "primary", address: "Poolemead Road", postcode: "BA2 1QR", eco_school_status: "silver", website: "www.twerton-infant-school.co.uk", created_at: "2016-12-10 14:58:30", updated_at: "2016-12-10 17:13:59", enrolled: true, urn: 109007, sash_id: 69, level: 0, calendar_id: 66, slug: "twerton-infant-school">
>>  @school.badges
=> [#<Merit::Badge id: 5, name: "eco-enrolled", level: nil, description: "Your school enrolled in the eco-school programme.", custom_fields: {}>]
```

I'm trying to get to a 100% reliable recreation, but its happened when editing schools. Am not sure what triggers is.

**Comment by ldodds** [comment]
I just had it trigger again whilst running an import. Wondering if there's some side effect with running the merit code separately to the application?

**Comment by ldodds** [comment]
More notes whilst I work on other things:

I was just working on some changes to a rails helper and found that the school homepage failed again.

It feels like something to do with code changes/reloading is causing the problem. It's possible it only manifests in development.

I've looked to see if there are any known issues but didn't find anything. This [stackoverflow issue](http://stackoverflow.com/questions/23081971/merit-gem-no-longer-works-on-rails-4-1) notes some issues, but I've tried accessing the custom fields directly but it doesn't work that way at all, only doted syntax.

**Comment by ldodds** [comment]
Yep, here's a reliable way to reproduce:

* In development environment go to a school with a badge
* Make a change to any rails helper, e.g. add a new line to application_helper.rb
* Hit reload on the school page, you'll get the error
* Restart the server and its fine

This is probably unlikely to bite in production, although without knowing the root cause its difficult to say.

**Comment by jamesjefferies** [comment]
Weird, I've see this too - restart local server and all fine!
