### ISSUE TITLE
Suggestion: Allow usage to be viewed in monetary amounts?

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#139]
From Phillip:

>we might also consider some form of crude monetary amount in the absence of the ability to change the y >axis (kWh,kWh/1000m2,kWh/100pupil,£,£/100pupil etc.) as previously discussed, for teaching purposes >assuming 12p/kWh for electricity, and 3p/kWh for gas – in the short-term hard-coded into the code would >be useful?

**Comment by chtowner** [comment]
Will be addressed by Y axis adjustments. Close
