### ISSUE TITLE
Date pickers not always working

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#221]
Date pickers aren't always working on the graphs.

E.g. http://www.energysparks.uk/schools/st-johns-catholic-primary-school-bath/usage?first_date=2017-06-06&period=hourly&to_date=2017-06-07#electricity

No date picker on electricity, but works on gas.

Whereas Twerton is fine on electricity.

**Comment by ldodds** [comment]
The issue is probably down to HTML error: using same id on elements on the gas & electricity tabs. Should add via a class selector instead.

**Comment by chtowner** [comment]
I was getting the same problem some of the time.
