### ISSUE TITLE
Date picker for hourly graphs not working correctly.

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#227]
If you change the  dates for  the  hourly usage graphs, the graph  does not adjust to the new dates. See example below.

![image](https://user-images.githubusercontent.com/29131441/27537884-98aac50a-5a6d-11e7-9430-ca91b4ceff40.png)

**Comment by ldodds** [comment]
Odd. The graphs are refreshing. And when I tested against Twerton, its all fine: the data does update.

But looking at Freshford its not. I'll do some digging later.

**Comment by ldodds** [comment]
I think its a bug when there's dual supplies. Should be simple to fix this evening.

**Comment by ldodds** [comment]
Have realised after more testing that this is still not fixed. Will investigate further tomorrow.
