### ISSUE TITLE
Child's introduction to the project

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#233]
Add a children's introduction to the project and where the data comes from? Current About page is geared towards adults. Could the top of the orange home page have 2 links - Pupils and Teachers, with each link taking the user to a different background introduction? The Teachers could be the  current About page. Will think of some suitable text for children.

**Comment by chtowner** [comment]
Here is the  suggested text.
[Child's Introduction to Energy Sparks.pdf](https://github.com/BathHacked/energy-sparks/files/1201064/Child.s.Introduction.to.Energy.Sparks.pdf)

**Comment by ldodds** [comment]
I've included this text into the application, for now its available from a "For pupils" link in the header navigation and footer. The "About" link is now "For teachers".

I'm intending to change some of the homepage so will include some links to these pages from there too.

I've left the text unchanged, but added some labelled sections to break up the text a bit. It's quite a lot of content for a single page.
