### ISSUE TITLE
Long meter descriptions drop off the side of the web page

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#236]
Long meter descriptions drop off the side of the web page, see Freshford School gas meters which has now been updated. Can the meter description field be bigger,  or have a wrap text option? In the Freshford case it is not really possible to write a shorter meter description which is useful.

**Comment by ldodds** [comment]
The text should be wrapping, will revisit once the new graph layout is released.

**Comment by ldodds** [comment]
@chtowner could I ask you to retest this on the test site (you may need to tweak some meter descriptions for one of the two schools).

The controls should resize appropriately, but there will be limits on how much text they can comfortably include. The name is intended to be a short title suitable for adding to a drop-down field. 

The Freshford titles are much longer than I was expecting to see and might still be problematic in the new layout. I'd suggest for Freshford using the main area, e.g. "School kitchen" as the title.

We might be better off with a shorter title and a separate description field which could be displayed somewhere else, e.g. as a tool tip or a separate key on the page.

**Comment by chtowner** [comment]
Tested and I think the new space and format is satisfactory for most meter names. However, I notice that although the descriptive text says for example "Graphing electricity consumption on Tuesday, 30 June 2015 for Test site north building and Test site south building", the key on the graphs uses the meter numbers. It is then not clear to students which meter number fits with which meter name/description, and hence which graph is which. Can the graph key also have the meter name/description if provided rather than the meter number as default?
