### ISSUE TITLE
Add background information or explanatory text to Charts pages.

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#237]
Could Charts pages have some background information or explanatory text on particular patterns and features to look out for when viewing the data, eg establishing baseloads and what would be contributing (eg fridges, freezers, servers etc), reasons for peak lunchtime consumption, weekend/winter holiday boiler cycling patterns? These issues are all discussed in the relevant Activity descriptions, but at the moment the Activities and their Descriptions feel quite disconnected from the Charts. Children thought it would be good if the website helped them to interpret the data more. Will supply some ideas.

**Comment by chtowner** [comment]
[Ideas for text on Chart's page.pdf](https://github.com/BathHacked/energy-sparks/files/1201061/Ideas.for.text.on.Chart.s.page.pdf)
Here are some suggested ideas in the attached document.

**Comment by ldodds** [comment]
I've added this text to the hourly charts for the moment. 

Should we have different text for the different charts or just use the same text?

**Comment by chtowner** [comment]
The hourly charts text is not all relevant to the weekly view charts. Will create some suitable text.
