### ISSUE TITLE
Chart's response to no data

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#240]
Charts should flag up when no data is available, rather than zero data, otherwise pupils were jumping to the conclusion that consumption was zero, when no data was recorded.

**Comment by ldodds** [comment]
The new date picker enforces minimum and maximum dates this should help reduce times when this occurs. Although its possible we might get gaps in data availability.

**Comment by ldodds** [comment]
May need to wait for #ankane/chartkick.js/pull/87 before fixing this.
