### ISSUE TITLE
Change colour of gas tab labelling to orange

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#243]
When you are in an electricity chart, the word Gas is highlighted in light blue at the top of the chart, so the children think the light blue chart is gas, not electricity – see screen shot below. 
![image](https://user-images.githubusercontent.com/29131441/28316924-b14cf230-6bbc-11e7-92a1-218d05d1d1b5.png)
Change link colour to the orange colour for gas

**Comment by ldodds** [comment]
Page layout has now changed. All colours are correctly set when changing supply.
