### ISSUE TITLE
Need to retain direct link button from School home page to Record a new Activity, even after first activity has been recorded

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#246]
Recording a new activity – Very hard to find how to do this from the school home page once you have recorded your first activity. The only way we could find to do this was via View Activities and then New Activity. Need to retain direct link button from School home page to Record a new Activity.

**Comment by ldodds** [comment]
There is already a link to "New Activity" on the school homepage after recording an activity.


![uploads/1b6768fd-fdeb-4c28-8192-274bfdc05fea/Screenshot from 2017-08-22 14-24-54.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F1b6768fd-fdeb-4c28-8192-274bfdc05fea%2FScreenshot+from+2017-08-22+14-24-54.png)
