### ISSUE TITLE
Add Link to Record activity from Activity description, perhaps via a 'Completed' link box.

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#250]
Link to Record activity from Activity description, perhaps via a 'Completed' link box. Otherwise children read the Activity description, and then have to remember which category it is in in order to Add the Activity. The children found it very hard to find their desired Activity from the Add Activity page, because they couldn't remember the Category, and found the long drop down list overwhelming and difficult to read.

**Comment by chtowner** [comment]
I can't see your updates to this on the test site. Not sure whether you have rolled out the code yet.

**Comment by ldodds** [comment]
I have released it. The link only applies if you're the administrator of a school (if your login is associated with a school). As an administrator you won't see it
