### ISSUE TITLE
Improve badge ordering sequence as a measure of attainment

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#256]
What happens when you get all the badges? Site should tell you what happens next....
Consider making all achieved badges visible on the school home page.
Possibly establish an order in which you gain badges, so it was clearer how well you were doing.

**Comment by ldodds** [comment]
We'll need to decide if something should happen when someone achieves all the badges, at the moment, with the revised list (#260) it'll need at least a full academic year of activities. Acknowledgement doesn't have to be another badge, could be some form of promotion or write-up?

20 badges will add a lot to the school homepage, will explore options for making badges more visible than they are currently.

The intention is that schools can self-direct a little to decide which badge to attempt next, but agree we could suggest some next steps. Perhaps include some indication of how close they are to achieving a badge.

**Comment by chtowner** [comment]
Close
