### ISSUE TITLE
Urgent fix needed - School admin users are not authorised to access the page accessed from Choose an Activity

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#293]
Urgent fix needed - School admin users are not authorised to access the page accessed from clicking on Choose an Activity from their school home page. The link works fine when I am logged in as an Admin user, but not when logged in as a School Admin user. I have been alerted to the problem by the Head of Pensford primary  who was testing out the site.

**Comment by ldodds** [comment]
I will fix this today, but won't be able to do a new release until late this evening.
