### ISSUE TITLE
Bug fix needed - Lorem ipsum text appearing against suggested activities on School's activity page

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#295]
Bug fix needed - Lorem ipsum text appearing against suggested activity description on School's activity page (http://www.energysparks.uk/schools/pensford-primary-school/suggest_activity). I think the title is sufficient in the suggested activity boxes, as not enough description will fit for it to be meaningful. Clicking on the boxes takes you to the correct description.

![image](https://user-images.githubusercontent.com/29131441/30373853-ae434e0a-987a-11e7-9f7a-ce6ddb837b02.png)

**Comment by ldodds** [comment]
Fixed and released.
