### ISSUE TITLE
Updating Recently your School used most energy on X to give full date

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#297]
With ongoing data availability issues, I wonder whether it would be more informative to have the text on the School home page stating "Recently your School used most energy on X" to give the full date rather than just the  day of the week. Otherwise, in the attached example it is unclear which Sunday it is referring to. Is it currently taking the last full week of data to determine which day to report? So the Sunday reported is Sunday 27th August, not Sunday 3rd August. Perhaps the actual date could be in a smaller font size, so the day of the week remains most prominent.

![image](https://user-images.githubusercontent.com/29131441/30375739-9df8cf1e-9881-11e7-8fc7-d9ca7a5074ea.png)

**Comment by chtowner** [comment]
On my visit to Pensford yesterday, this issue caused confusion, so is definitely worth addressing. I was visiting on a Wednesday, so the children automatically thought the statement was referring to the previous day, when in fact it was the previous Tuesday, because there was no data for the previous day yet. 

It might be good to clarify what 'Recently' means too. Could 'Within the last 2 weeks' be clearer?

**Comment by jamesjefferies** [comment]
Fixed in #335
