### ISSUE TITLE
How is the Data Scientist Award triggered?

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#305]
Is the Data Scientist Award triggered automatically, and if so how?

**Comment by ldodds** [comment]
It's triggered automatically. At the moment its whenever a school completes the "Pupils use energy data during maths lessons" activity (id 6 on the live site).

The code looks to see which activity type has a "badge name" of "data-scientist", then awards badge when one or more of those activities are created. The badge name is configured on the edit page.
