### ISSUE TITLE
Exclude meters from individual schools pick lists if there is no AMR data for them

### ISSUE THREAD

**Issue by chtowner** [BathHacked/energy-sparks#309]
Can we exclude meters from individual schools pick lists if there is no AMR data for them? At the moment you can compare meters where no data exists for a particular meter eg for Saltford or Freshford, and I think this is confusing if a child chooses the meter with no data.

**Comment by chtowner** [comment]
It is still helpful to keep the meters with no data in the loading report list so that we have a simple of way of knowing that the AMR data record for the school is incomplete, but I don't think the children need to be able to pick meters with no data.

**Comment by ldodds** [comment]
As discussed on Friday, I've removed meters that are marked as not active (in the admin interface) from the graphs. So these won't appear in the pick lists for filtering and comparison.

If a meter had previously had data, but has become inactive then its usage will still be included in any totals, it just won't be displayed. Need to bear this in mind with future meter changes. 

But for Freshford and Saltford, which both have meters than have no data at all in the current system, this shouldn't be a problem.
