### ISSUE TITLE
Metric: average weekday daily usage

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#42]
This is a spec for a metric to display on a school homepage: what's the average amount of electricity (or gas) that they use during the week?

The card should read something like:

52kWh
is how much energy you use on a school day

The system should calculate this by looking at the last full week's worth of data and calculating the average daily use of electricity (or gas) during a week day (Mon-Friday), summing across all meters.

**Comment by dynamicworkplace** [comment]
@ldodds can we assume that if the Friday has readings then we have a full week's readings?

**Comment by ldodds** [comment]
Yes, thats a reasonable assumption
