### ISSUE TITLE
Revise list of schools to distinguish between enrolled schools and eligible schools

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#50]
On the list of schools page, distinguish between schools that are enrolled and those that are just eligible (initially all local primary schools, eventually all B&NES schools).

There should be a strong visual indicator, suggest splitting the page into:

* Participating schools (list of cards as it is now)
* Eligible schools as a separate, less prominent list further down the page.

**Comment by dynamicworkplace** [comment]
closed by PR#61
