### ISSUE TITLE
Create basic data model for schools, meters, usage data

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#6]
A School has a type and an address. 

A School can have many Meters. Over time (meters are replaced), or separate meters for specific buildings on the site.

A Meter is either for gas or electricity usage. It belongs to a school. A meter can have a parent. A meter has a (installation) start date and an end date. (Meters can be replaced)

A Meter Reading records a specific energy usage value for a single meter at a point in time (we will be collecting data in half hourly increments. Use a date-time value).

Because a school can have many electricity and gas meters, there needs to be a single parent ("virtual") meter can gathers together the aggregated readings for all currently live meters.

A School will have at most 1 virtual gas meter and at most 1 virtual electricity meter.

Initial active record models should look something like:

* [ ] School: name, type (primary, secondary, etc), address, postcode
* [ ] Meter: type (gas, electricity), school, parent meter, virtual (yes, no)
* [ ] Meter Reading: meter,  reading time, value, units, start date, end date

We may later add some columns to the Meter Reading to identify whether the reading was taken during the school day, during term time, etc. While these can be calculated from the date-time of the reading, it may be more efficient to compute during import.

**Comment by ldodds** [comment]
## School

* Name (string)
* Systems Link Id (string)
* Type (primary, secondary, ...) (integer)
* Address (string)
* Postcode (string)
* Eco school status (integer)
* Website

## Meter

* Systems Link Id (integer)
* Type (gas, electricity) (integer)
* School Id

## Meter Reading

* Meter Id (integer)
* Reading Time (date-time)
* Value (float)
* Units (kWh, ...) (string)

**Comment by dynamicworkplace** [comment]
Amended models as discussed and PR submitted.
