### ISSUE TITLE
Allow user to be associated with an enrolled school

### ISSUE THREAD

**Issue by ldodds** [BathHacked/energy-sparks#84]
Edit a user, it looks like it only shows enrolled schools. As part of setup, it would be useful to associate them with a school that is not yet enrolled.

**Comment by dynamicworkplace** [comment]
Not a problem to change, but I thought this would avoid assigning to a school that isn't participating yet - the user won't be able to do anything until the school is enrolled (the show school page now goes to the Enrol page), so I thought enrolling the school then assigning the user would be the normal procedure.

**Comment by dynamicworkplace** [comment]
@ldodds User can be now be assigned to a school that hasn't enrolled. Redirect of the school page to enrol does not now occur if the user can manage the school.
